[package]
name = "kurumi-containerd-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
crossterm = "0.29"
kurumi-containerd-config = { path = "../kurumi-containerd-config" }
kurumi-containerd-runtime = { path = "../kurumi-containerd-runtime" }
ratatui = "0.30"
tempfile.workspace = true
which.workspace = true
uuid.workspace = true

[lints]
workspace = true
