[workspace]
members = [
  "crates/kurumi-containerd-cli",
  "crates/kurumi-containerd-config",
  "crates/kurumi-containerd-helper",
  "crates/kurumi-containerd-runtime",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
anyhow = "1.0"
bitflags = "2.9"
clap = { version = "4.5", features = ["derive", "env"] }
fs2 = "0.4"
flate2 = { version = "1.1", default-features = false, features = [
  "rust_backend",
] }
kurumi-containerd-helper = { path = "crates/kurumi-containerd-helper" }
libc = "0.2"
mio = { version = "1.0", features = ["os-poll", "os-ext"] }
procfs = { version = "0.18", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.20"
tar = "0.4"
toml = "1.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.17", features = ["v4", "serde"] }
which = "8.0.5"
xz2 = "0.1"
zip = { version = "8.6", default-features = false, features = ["deflate"] }
zstd = { version = "0.14", default-features = false }

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1

