[package]
name = "kurumi-containerd-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fs2.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
kurumi-containerd-error.workspace = true
toml.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
